<<: !include ../../hpack-defaults.yaml

name: tix-to-markdown
synopsis: Convert HPC .tix files to markdown coverage reports
description: A utility tool for converting Haskell HPC .tix files to markdown-formatted coverage reports

dependencies:
- base >= 4.7 && < 5
- hpc >= 0.6
- containers >= 0.6
- filepath >= 1.4

executables:
  tix-to-markdown:
    main: Main.hs
    source-dirs: .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
