defaults:
  local: ../hpack-common/defaults.yaml

verbatim: { cabal-version: 3.0 }

name:         temporal-sdk-codec-server
version:      "0.0.1.0"
author:       Ian Duncan
maintainer:   temporal@mercury.com
license-file: LICENSE
license:      BSD-3-Clause
build-type:   Simple
language:     Haskell2010

dependencies:
- base
- temporal-sdk
- bytestring
- wai
- aeson
- containers
- hs-opentelemetry-api
- transformers
- http-types
- text
- vector
- wai-cors

library:
  source-dirs: src
  other-modules: []
