{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# OPTIONS_GHC -Wno-unused-imports -Wno-unused-matches -Wno-unused-top-binds #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# OPTIONS_GHC -Wno-ambiguous-fields #-}
-- | Auto-generated protobuf types from package @coresdk.external_data@.
--
-- __THIS FILE IS AUTO-GENERATED BY wireform. DO NOT EDIT.__
--
-- Any manual changes will be overwritten the next time code
-- generation is run.  To modify the types or instances, edit the
-- @.proto@ source file and re-run the code generator.
module Proto.Temporal.Sdk.Core.ExternalData.ExternalData where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Wireform.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Encode
import Proto.Decode
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.Internal.JSON (jsonObject, (.=:), parseFieldMaybe, bytesFieldToJSON, parseBytesFieldMaybe, bytesMapFieldToJSON, parseBytesMapFieldMaybe, protoBytesToJSON)
import Data.Proxy (Proxy(..))
import Data.Reflection (Given(..), given)
import Proto.Internal.JSON.Extension qualified as PJExt
import Proto.Schema (ProtoMessage(..), SomeFieldDescriptor(..), FieldDescriptor(..), FieldTypeDescriptor(..), ScalarFieldType(..), FieldLabel'(..))
import Proto.Registry (IsMessage)
import Proto.Registry qualified
import qualified Proto.Extension
import Proto.Internal.Wire (Tag(..), WireType(..))
import Proto.Internal.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)
import Proto.Internal.Encode.Archetype (archVarint, archSVarint32, archSVarint64,
  archFixed32, archFixed64, archFloat, archDouble, archBool,
  archString, archBytes, archSubmessage,
  archVarintSize, archStringSize, archBytesSize, archBoolSize,
  archFixed32Size, archFixed64Size, archSubmessageSize)
import qualified Proto.Google.Protobuf.Duration as PB_Duration
import qualified Proto.Google.Protobuf.Timestamp as PB_Timestamp

-- | Serialized FileDescriptorProto for this .proto file.
-- Decode with @Proto.Google.Protobuf.Descriptor.decodeMessage@.
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = "\x0a\x33\x74\x65\x6d\x70\x6f\x72\x61\x6c\x2f\x73\x64\x6b\x2f\x63\x6f\x72\x65\x2f\x65\x78\x74\x65\x72\x6e\x61\x6c\x5f\x64\x61\x74\x61\x2f\x65\x78\x74\x65\x72\x6e\x61\x6c\x5f\x64\x61\x74\x61\x2e\x70\x72\x6f\x74\x6f\x12\x15\x63\x6f\x72\x65\x73\x64\x6b\x2e\x65\x78\x74\x65\x72\x6e\x61\x6c\x5f\x64\x61\x74\x61\x1a\x1e\x67\x6f\x6f\x67\x6c\x65\x2f\x70\x72\x6f\x74\x6f\x62\x75\x66\x2f\x64\x75\x72\x61\x74\x69\x6f\x6e\x2e\x70\x72\x6f\x74\x6f\x1a\x1f\x67\x6f\x6f\x67\x6c\x65\x2f\x70\x72\x6f\x74\x6f\x62\x75\x66\x2f\x74\x69\x6d\x65\x73\x74\x61\x6d\x70\x2e\x70\x72\x6f\x74\x6f\x22\xfb\x01\x0a\x17\x4c\x6f\x63\x61\x6c\x41\x63\x74\x69\x76\x69\x74\x79\x4d\x61\x72\x6b\x65\x72\x44\x61\x74\x61\x12\x0b\x0a\x03\x73\x65\x71\x18\x01\x20\x01\x28\x0d\x12\x0f\x0a\x07\x61\x74\x74\x65\x6d\x70\x74\x18\x02\x20\x01\x28\x0d\x12\x13\x0a\x0b\x61\x63\x74\x69\x76\x69\x74\x79\x5f\x69\x64\x18\x03\x20\x01\x28\x09\x12\x15\x0a\x0d\x61\x63\x74\x69\x76\x69\x74\x79\x5f\x74\x79\x70\x65\x18\x04\x20\x01\x28\x09\x12\x30\x0a\x0d\x63\x6f\x6d\x70\x6c\x65\x74\x65\x5f\x74\x69\x6d\x65\x18\x05\x20\x01\x28\x0b\x32\x19\x67\x6f\x6f\x67\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x62\x75\x66\x2e\x54\x69\x6d\x65\x73\x74\x61\x6d\x70\x12\x29\x0a\x07\x62\x61\x63\x6b\x6f\x66\x66\x18\x06\x20\x01\x28\x0b\x32\x18\x67\x6f\x6f\x67\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x62\x75\x66\x2e\x44\x75\x72\x61\x74\x69\x6f\x6e\x12\x39\x0a\x16\x6f\x72\x69\x67\x69\x6e\x61\x6c\x5f\x73\x63\x68\x65\x64\x75\x6c\x65\x5f\x74\x69\x6d\x65\x18\x07\x20\x01\x28\x0b\x32\x19\x67\x6f\x6f\x67\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x62\x75\x66\x2e\x54\x69\x6d\x65\x73\x74\x61\x6d\x70\x22\x33\x0a\x11\x50\x61\x74\x63\x68\x65\x64\x4d\x61\x72\x6b\x65\x72\x44\x61\x74\x61\x12\x0a\x0a\x02\x69\x64\x18\x01\x20\x01\x28\x09\x12\x12\x0a\x0a\x64\x65\x70\x72\x65\x63\x61\x74\x65\x64\x18\x02\x20\x01\x28\x08\x62\x06\x70\x72\x6f\x74\x6f\x33"


data LocalActivityMarkerData = LocalActivityMarkerData
  { seq :: !(Maybe Word32)
  , attempt :: !(Maybe Word32)
  , activityId :: !(Maybe Text)
  , activityType :: !(Maybe Text)
  , completeTime :: !(Maybe PB_Timestamp.Timestamp)
  , backoff :: !(Maybe PB_Duration.Duration)
  , originalScheduleTime :: !(Maybe PB_Timestamp.Timestamp)
  , localActivityMarkerDataUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultLocalActivityMarkerData :: LocalActivityMarkerData
defaultLocalActivityMarkerData = LocalActivityMarkerData
  { seq = Nothing
  , attempt = Nothing
  , activityId = Nothing
  , activityType = Nothing
  , completeTime = Nothing
  , backoff = Nothing
  , originalScheduleTime = Nothing
  , localActivityMarkerDataUnknownFields = []
  }

instance MessageEncode LocalActivityMarkerData where
  buildMessage msg =
    (maybe mempty (\v -> archVarint 8 (fromIntegral v)) msg.seq)
    <> (maybe mempty (\v -> archVarint 16 (fromIntegral v)) msg.attempt)
    <> (maybe mempty (\v -> archString 26 v) msg.activityId)
    <> (maybe mempty (\v -> archString 34 v) msg.activityType)
    <> (maybe mempty (\v -> let sz = messageSize v in archSubmessage 42 sz (buildMessage v)) msg.completeTime)
    <> (maybe mempty (\v -> let sz = messageSize v in archSubmessage 50 sz (buildMessage v)) msg.backoff)
    <> (maybe mempty (\v -> let sz = messageSize v in archSubmessage 58 sz (buildMessage v)) msg.originalScheduleTime)
    <> encodeUnknownFields msg.localActivityMarkerDataUnknownFields

instance MessageSize LocalActivityMarkerData where
  messageSize msg =
    (maybe 0 (\v -> archVarintSize (fromIntegral v)) msg.seq)
    + (maybe 0 (\v -> archVarintSize (fromIntegral v)) msg.attempt)
    + (maybe 0 (\v -> archStringSize v) msg.activityId)
    + (maybe 0 (\v -> archStringSize v) msg.activityType)
    + (maybe 0 (\v -> archSubmessageSize (messageSize v)) msg.completeTime)
    + (maybe 0 (\v -> archSubmessageSize (messageSize v)) msg.backoff)
    + (maybe 0 (\v -> archSubmessageSize (messageSize v)) msg.originalScheduleTime)
    + unknownFieldsSize msg.localActivityMarkerDataUnknownFields

instance MessageDecode LocalActivityMarkerData where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop Nothing Nothing Nothing Nothing Nothing Nothing Nothing []
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_unknown_ = withTagM
        (pure (LocalActivityMarkerData {seq = acc_0, attempt = acc_1, activityId = acc_2, activityType = acc_3, completeTime = acc_4, backoff = acc_5, originalScheduleTime = acc_6, localActivityMarkerDataUnknownFields = reverse acc_unknown_}))
        (\fn wt -> case fn of
          1 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop (Just v) acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 acc_unknown_
          2 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop acc_0 (Just v) acc_2 acc_3 acc_4 acc_5 acc_6 acc_unknown_
          3 -> do
            v <- decodeFieldString
            loop acc_0 acc_1 (Just v) acc_3 acc_4 acc_5 acc_6 acc_unknown_
          4 -> do
            v <- decodeFieldString
            loop acc_0 acc_1 acc_2 (Just v) acc_4 acc_5 acc_6 acc_unknown_
          5 -> do
            v <- decodeFieldMessage
            loop acc_0 acc_1 acc_2 acc_3 (Just v) acc_5 acc_6 acc_unknown_
          6 -> do
            v <- decodeFieldMessage
            loop acc_0 acc_1 acc_2 acc_3 acc_4 (Just v) acc_6 acc_unknown_
          7 -> do
            v <- decodeFieldMessage
            loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 (Just v) acc_unknown_
          _ -> do
            uf <- captureUnknownField fn (toEnum wt)
            loop acc_0 acc_1 acc_2 acc_3 acc_4 acc_5 acc_6 (uf : acc_unknown_))

instance ProtoMessage LocalActivityMarkerData where
  protoMessageName _ = "coresdk.external_data.LocalActivityMarkerData"
  protoPackageName _ = "coresdk.external_data"
  protoDefaultValue = defaultLocalActivityMarkerData
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "seq"
        , fdNumber = 1
        , fdTypeDesc = ScalarType UInt32Field
        , fdLabel = LabelOptional
        , fdGet = \(m :: LocalActivityMarkerData) -> m.seq
        , fdSet = \v (m :: LocalActivityMarkerData) -> (m { seq = v } :: LocalActivityMarkerData)
        }), (2, SomeField FieldDescriptor
        { fdName = "attempt"
        , fdNumber = 2
        , fdTypeDesc = ScalarType UInt32Field
        , fdLabel = LabelOptional
        , fdGet = \(m :: LocalActivityMarkerData) -> m.attempt
        , fdSet = \v (m :: LocalActivityMarkerData) -> (m { attempt = v } :: LocalActivityMarkerData)
        })
    , (3, SomeField FieldDescriptor
        { fdName = "activity_id"
        , fdNumber = 3
        , fdTypeDesc = ScalarType StringField
        , fdLabel = LabelOptional
        , fdGet = \(m :: LocalActivityMarkerData) -> m.activityId
        , fdSet = \v (m :: LocalActivityMarkerData) -> (m { activityId = v } :: LocalActivityMarkerData)
        })
    , (4, SomeField FieldDescriptor
        { fdName = "activity_type"
        , fdNumber = 4
        , fdTypeDesc = ScalarType StringField
        , fdLabel = LabelOptional
        , fdGet = \(m :: LocalActivityMarkerData) -> m.activityType
        , fdSet = \v (m :: LocalActivityMarkerData) -> (m { activityType = v } :: LocalActivityMarkerData)
        })
    , (5, SomeField FieldDescriptor
        { fdName = "complete_time"
        , fdNumber = 5
        , fdTypeDesc = MessageType "google.protobuf.Timestamp"
        , fdLabel = LabelOptional
        , fdGet = \(m :: LocalActivityMarkerData) -> m.completeTime
        , fdSet = \v (m :: LocalActivityMarkerData) -> (m { completeTime = v } :: LocalActivityMarkerData)
        })
    , (6, SomeField FieldDescriptor
        { fdName = "backoff"
        , fdNumber = 6
        , fdTypeDesc = MessageType "google.protobuf.Duration"
        , fdLabel = LabelOptional
        , fdGet = \(m :: LocalActivityMarkerData) -> m.backoff
        , fdSet = \v (m :: LocalActivityMarkerData) -> (m { backoff = v } :: LocalActivityMarkerData)
        })
    , (7, SomeField FieldDescriptor
        { fdName = "original_schedule_time"
        , fdNumber = 7
        , fdTypeDesc = MessageType "google.protobuf.Timestamp"
        , fdLabel = LabelOptional
        , fdGet = \(m :: LocalActivityMarkerData) -> m.originalScheduleTime
        , fdSet = \v (m :: LocalActivityMarkerData) -> (m { originalScheduleTime = v } :: LocalActivityMarkerData)
        })
    ]

instance IsMessage LocalActivityMarkerData

instance Aeson.ToJSON LocalActivityMarkerData where
  toJSON msg = jsonObject
      [ "seq" .=: msg.seq
      , "attempt" .=: msg.attempt
      , "activityId" .=: msg.activityId
      , "activityType" .=: msg.activityType
      , "completeTime" .=: msg.completeTime
      , "backoff" .=: msg.backoff
      , "originalScheduleTime" .=: msg.originalScheduleTime
      ]

instance Aeson.FromJSON LocalActivityMarkerData where
  parseJSON = Aeson.withObject "LocalActivityMarkerData" $ \obj -> do
    fld_seq <- parseFieldMaybe obj "seq"
    fld_attempt <- parseFieldMaybe obj "attempt"
    fld_activityId <- parseFieldMaybe obj "activityId"
    fld_activityType <- parseFieldMaybe obj "activityType"
    fld_completeTime <- parseFieldMaybe obj "completeTime"
    fld_backoff <- parseFieldMaybe obj "backoff"
    fld_originalScheduleTime <- parseFieldMaybe obj "originalScheduleTime"
    pure (defaultLocalActivityMarkerData
      { seq = maybe (defaultLocalActivityMarkerData.seq) Prelude.id fld_seq
      , attempt = maybe (defaultLocalActivityMarkerData.attempt) Prelude.id fld_attempt
      , activityId = maybe (defaultLocalActivityMarkerData.activityId) Prelude.id fld_activityId
      , activityType = maybe (defaultLocalActivityMarkerData.activityType) Prelude.id fld_activityType
      , completeTime = maybe (defaultLocalActivityMarkerData.completeTime) Prelude.id fld_completeTime
      , backoff = maybe (defaultLocalActivityMarkerData.backoff) Prelude.id fld_backoff
      , originalScheduleTime = maybe (defaultLocalActivityMarkerData.originalScheduleTime) Prelude.id fld_originalScheduleTime
      , localActivityMarkerDataUnknownFields = []
      } :: LocalActivityMarkerData)

instance Hashable LocalActivityMarkerData where
  hashWithSalt salt msg = hashWithSalt (hashWithSalt (hashWithSalt (hashWithSalt (hashWithSalt (hashWithSalt (hashWithSalt (salt) msg.seq) msg.attempt) msg.activityId) msg.activityType) msg.completeTime) msg.backoff) msg.originalScheduleTime

instance Proto.Extension.HasExtensions LocalActivityMarkerData where
  messageUnknownFields msg = msg.localActivityMarkerDataUnknownFields
  setMessageUnknownFields !ufs msg = msg { localActivityMarkerDataUnknownFields = ufs }

instance Semigroup LocalActivityMarkerData where
  a <> b = LocalActivityMarkerData
    { seq = case b.seq of { Nothing -> a.seq; x -> x }
    , attempt = case b.attempt of { Nothing -> a.attempt; x -> x }
    , activityId = case b.activityId of { Nothing -> a.activityId; x -> x }
    , activityType = case b.activityType of { Nothing -> a.activityType; x -> x }
    , completeTime = case b.completeTime of { Nothing -> a.completeTime; x -> x }
    , backoff = case b.backoff of { Nothing -> a.backoff; x -> x }
    , originalScheduleTime = case b.originalScheduleTime of { Nothing -> a.originalScheduleTime; x -> x }
    , localActivityMarkerDataUnknownFields = a.localActivityMarkerDataUnknownFields <> b.localActivityMarkerDataUnknownFields
    }

instance Monoid LocalActivityMarkerData where
  mempty = defaultLocalActivityMarkerData

data PatchedMarkerData = PatchedMarkerData
  { id :: !(Maybe Text)
  , deprecated :: !(Maybe Bool)
  , patchedMarkerDataUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultPatchedMarkerData :: PatchedMarkerData
defaultPatchedMarkerData = PatchedMarkerData
  { id = Nothing
  , deprecated = Nothing
  , patchedMarkerDataUnknownFields = []
  }

instance MessageEncode PatchedMarkerData where
  buildMessage msg =
    (maybe mempty (\v -> archString 10 v) msg.id)
    <> (maybe mempty (\v -> archBool 16 v) msg.deprecated)
    <> encodeUnknownFields msg.patchedMarkerDataUnknownFields

instance MessageSize PatchedMarkerData where
  messageSize msg =
    (maybe 0 (\v -> archStringSize v) msg.id)
    + (maybe 0 (\v -> archBoolSize) msg.deprecated)
    + unknownFieldsSize msg.patchedMarkerDataUnknownFields

instance MessageDecode PatchedMarkerData where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop Nothing Nothing []
    where
      loop acc_0 acc_1 acc_unknown_ = withTagM
        (pure (PatchedMarkerData {id = acc_0, deprecated = acc_1, patchedMarkerDataUnknownFields = reverse acc_unknown_}))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldString
            loop (Just v) acc_1 acc_unknown_
          2 -> do
            v <- decodeFieldBool
            loop acc_0 (Just v) acc_unknown_
          _ -> do
            uf <- captureUnknownField fn (toEnum wt)
            loop acc_0 acc_1 (uf : acc_unknown_))

instance ProtoMessage PatchedMarkerData where
  protoMessageName _ = "coresdk.external_data.PatchedMarkerData"
  protoPackageName _ = "coresdk.external_data"
  protoDefaultValue = defaultPatchedMarkerData
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "id"
        , fdNumber = 1
        , fdTypeDesc = ScalarType StringField
        , fdLabel = LabelOptional
        , fdGet = \(m :: PatchedMarkerData) -> m.id
        , fdSet = \v (m :: PatchedMarkerData) -> (m { id = v } :: PatchedMarkerData)
        }), (2, SomeField FieldDescriptor
        { fdName = "deprecated"
        , fdNumber = 2
        , fdTypeDesc = ScalarType BoolField
        , fdLabel = LabelOptional
        , fdGet = \(m :: PatchedMarkerData) -> m.deprecated
        , fdSet = \v (m :: PatchedMarkerData) -> (m { deprecated = v } :: PatchedMarkerData)
        })
    ]

instance IsMessage PatchedMarkerData

instance Aeson.ToJSON PatchedMarkerData where
  toJSON msg = jsonObject
      [ "id" .=: msg.id
      , "deprecated" .=: msg.deprecated
      ]

instance Aeson.FromJSON PatchedMarkerData where
  parseJSON = Aeson.withObject "PatchedMarkerData" $ \obj -> do
    fld_id <- parseFieldMaybe obj "id"
    fld_deprecated <- parseFieldMaybe obj "deprecated"
    pure (defaultPatchedMarkerData
      { id = maybe (defaultPatchedMarkerData.id) Prelude.id fld_id
      , deprecated = maybe (defaultPatchedMarkerData.deprecated) Prelude.id fld_deprecated
      , patchedMarkerDataUnknownFields = []
      } :: PatchedMarkerData)

instance Hashable PatchedMarkerData where
  hashWithSalt salt msg = hashWithSalt (hashWithSalt (salt) msg.id) msg.deprecated

instance Proto.Extension.HasExtensions PatchedMarkerData where
  messageUnknownFields msg = msg.patchedMarkerDataUnknownFields
  setMessageUnknownFields !ufs msg = msg { patchedMarkerDataUnknownFields = ufs }

instance Semigroup PatchedMarkerData where
  a <> b = PatchedMarkerData
    { id = case b.id of { Nothing -> a.id; x -> x }
    , deprecated = case b.deprecated of { Nothing -> a.deprecated; x -> x }
    , patchedMarkerDataUnknownFields = a.patchedMarkerDataUnknownFields <> b.patchedMarkerDataUnknownFields
    }

instance Monoid PatchedMarkerData where
  mempty = defaultPatchedMarkerData
