{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# OPTIONS_GHC -Wno-unused-imports -Wno-unused-matches -Wno-unused-top-binds #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# OPTIONS_GHC -Wno-ambiguous-fields #-}
-- | Auto-generated protobuf types from package @temporal.api.sdk.v1@.
--
-- __THIS FILE IS AUTO-GENERATED BY wireform. DO NOT EDIT.__
--
-- Any manual changes will be overwritten the next time code
-- generation is run.  To modify the types or instances, edit the
-- @.proto@ source file and re-run the code generator.
module Proto.Temporal.Api.Sdk.V1.WorkerConfig where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Wireform.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Encode
import Proto.Decode
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.Internal.JSON (jsonObject, (.=:), parseFieldMaybe, bytesFieldToJSON, parseBytesFieldMaybe, bytesMapFieldToJSON, parseBytesMapFieldMaybe, protoBytesToJSON)
import Data.Proxy (Proxy(..))
import Data.Reflection (Given(..), given)
import Proto.Internal.JSON.Extension qualified as PJExt
import Proto.Schema (ProtoMessage(..), SomeFieldDescriptor(..), FieldDescriptor(..), FieldTypeDescriptor(..), ScalarFieldType(..), FieldLabel'(..))
import Proto.Registry (IsMessage)
import Proto.Registry qualified
import qualified Proto.Extension
import Proto.Internal.Wire (Tag(..), WireType(..))
import Proto.Internal.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)
import Proto.Internal.Encode.Archetype (archVarint, archSVarint32, archSVarint64,
  archFixed32, archFixed64, archFloat, archDouble, archBool,
  archString, archBytes, archSubmessage,
  archVarintSize, archStringSize, archBytesSize, archBoolSize,
  archFixed32Size, archFixed64Size, archSubmessageSize)

-- | Serialized FileDescriptorProto for this .proto file.
-- Decode with @Proto.Google.Protobuf.Descriptor.decodeMessage@.
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = "\x0a\x27\x74\x65\x6d\x70\x6f\x72\x61\x6c\x2f\x61\x70\x69\x2f\x73\x64\x6b\x2f\x76\x31\x2f\x77\x6f\x72\x6b\x65\x72\x5f\x63\x6f\x6e\x66\x69\x67\x2e\x70\x72\x6f\x74\x6f\x12\x13\x74\x65\x6d\x70\x6f\x72\x61\x6c\x2e\x61\x70\x69\x2e\x73\x64\x6b\x2e\x76\x31\x22\x83\x03\x0a\x0c\x57\x6f\x72\x6b\x65\x72\x43\x6f\x6e\x66\x69\x67\x12\x1b\x0a\x13\x77\x6f\x72\x6b\x66\x6c\x6f\x77\x5f\x63\x61\x63\x68\x65\x5f\x73\x69\x7a\x65\x18\x01\x20\x01\x28\x05\x12\x55\x0a\x16\x73\x69\x6d\x70\x6c\x65\x5f\x70\x6f\x6c\x6c\x65\x72\x5f\x62\x65\x68\x61\x76\x69\x6f\x72\x18\x02\x20\x01\x28\x0b\x32\x35\x74\x65\x6d\x70\x6f\x72\x61\x6c\x2e\x61\x70\x69\x2e\x73\x64\x6b\x2e\x76\x31\x2e\x57\x6f\x72\x6b\x65\x72\x43\x6f\x6e\x66\x69\x67\x2e\x53\x69\x6d\x70\x6c\x65\x50\x6f\x6c\x6c\x65\x72\x42\x65\x68\x61\x76\x69\x6f\x72\x12\x5f\x0a\x1b\x61\x75\x74\x6f\x73\x63\x61\x6c\x69\x6e\x67\x5f\x70\x6f\x6c\x6c\x65\x72\x5f\x62\x65\x68\x61\x76\x69\x6f\x72\x18\x03\x20\x01\x28\x0b\x32\x3a\x74\x65\x6d\x70\x6f\x72\x61\x6c\x2e\x61\x70\x69\x2e\x73\x64\x6b\x2e\x76\x31\x2e\x57\x6f\x72\x6b\x65\x72\x43\x6f\x6e\x66\x69\x67\x2e\x41\x75\x74\x6f\x73\x63\x61\x6c\x69\x6e\x67\x50\x6f\x6c\x6c\x65\x72\x42\x65\x68\x61\x76\x69\x6f\x72\x1a\x2b\x0a\x14\x53\x69\x6d\x70\x6c\x65\x50\x6f\x6c\x6c\x65\x72\x42\x65\x68\x61\x76\x69\x6f\x72\x12\x13\x0a\x0b\x6d\x61\x78\x5f\x70\x6f\x6c\x6c\x65\x72\x73\x18\x01\x20\x01\x28\x05\x1a\x5e\x0a\x19\x41\x75\x74\x6f\x73\x63\x61\x6c\x69\x6e\x67\x50\x6f\x6c\x6c\x65\x72\x42\x65\x68\x61\x76\x69\x6f\x72\x12\x13\x0a\x0b\x6d\x69\x6e\x5f\x70\x6f\x6c\x6c\x65\x72\x73\x18\x01\x20\x01\x28\x05\x12\x13\x0a\x0b\x6d\x61\x78\x5f\x70\x6f\x6c\x6c\x65\x72\x73\x18\x02\x20\x01\x28\x05\x12\x17\x0a\x0f\x69\x6e\x69\x74\x69\x61\x6c\x5f\x70\x6f\x6c\x6c\x65\x72\x73\x18\x03\x20\x01\x28\x05\x42\x11\x0a\x0f\x70\x6f\x6c\x6c\x65\x72\x5f\x62\x65\x68\x61\x76\x69\x6f\x72\x62\x06\x70\x72\x6f\x74\x6f\x33"


data WorkerConfig = WorkerConfig
  { workflowCacheSize :: !(Maybe Int32)
  , pollerBehavior :: !(Maybe WorkerConfig'PollerBehavior)
  , workerConfigUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

data WorkerConfig'SimplePollerBehavior = WorkerConfig'SimplePollerBehavior
  { maxPollers :: !(Maybe Int32)
  , workerConfigSimplePollerBehaviorUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultWorkerConfig'SimplePollerBehavior :: WorkerConfig'SimplePollerBehavior
defaultWorkerConfig'SimplePollerBehavior = WorkerConfig'SimplePollerBehavior
  { maxPollers = Nothing
  , workerConfigSimplePollerBehaviorUnknownFields = []
  }

instance MessageEncode WorkerConfig'SimplePollerBehavior where
  buildMessage msg =
    (maybe mempty (\v -> archVarint 8 (fromIntegral v)) msg.maxPollers)
    <> encodeUnknownFields msg.workerConfigSimplePollerBehaviorUnknownFields

instance MessageSize WorkerConfig'SimplePollerBehavior where
  messageSize msg =
    (maybe 0 (\v -> archVarintSize (fromIntegral v)) msg.maxPollers)
    + unknownFieldsSize msg.workerConfigSimplePollerBehaviorUnknownFields

instance MessageDecode WorkerConfig'SimplePollerBehavior where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop Nothing []
    where
      loop acc_0 acc_unknown_ = withTagM
        (pure (WorkerConfig'SimplePollerBehavior {maxPollers = acc_0, workerConfigSimplePollerBehaviorUnknownFields = reverse acc_unknown_}))
        (\fn wt -> case fn of
          1 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop (Just v) acc_unknown_
          _ -> do
            uf <- captureUnknownField fn (toEnum wt)
            loop acc_0 (uf : acc_unknown_))

instance ProtoMessage WorkerConfig'SimplePollerBehavior where
  protoMessageName _ = "temporal.api.sdk.v1.WorkerConfig.SimplePollerBehavior"
  protoPackageName _ = "temporal.api.sdk.v1"
  protoDefaultValue = defaultWorkerConfig'SimplePollerBehavior
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "max_pollers"
        , fdNumber = 1
        , fdTypeDesc = ScalarType Int32Field
        , fdLabel = LabelOptional
        , fdGet = \(m :: WorkerConfig'SimplePollerBehavior) -> m.maxPollers
        , fdSet = \v (m :: WorkerConfig'SimplePollerBehavior) -> (m { maxPollers = v } :: WorkerConfig'SimplePollerBehavior)
        })
    ]

instance IsMessage WorkerConfig'SimplePollerBehavior

instance Aeson.ToJSON WorkerConfig'SimplePollerBehavior where
  toJSON msg = jsonObject
      [ "maxPollers" .=: msg.maxPollers

      ]

instance Aeson.FromJSON WorkerConfig'SimplePollerBehavior where
  parseJSON = Aeson.withObject "WorkerConfig'SimplePollerBehavior" $ \obj -> do
    fld_maxPollers <- parseFieldMaybe obj "maxPollers"
    pure (defaultWorkerConfig'SimplePollerBehavior
      { maxPollers = maybe (defaultWorkerConfig'SimplePollerBehavior.maxPollers) Prelude.id fld_maxPollers
      , workerConfigSimplePollerBehaviorUnknownFields = []
      } :: WorkerConfig'SimplePollerBehavior)

instance Hashable WorkerConfig'SimplePollerBehavior where
  hashWithSalt salt msg = hashWithSalt (salt) msg.maxPollers

instance Proto.Extension.HasExtensions WorkerConfig'SimplePollerBehavior where
  messageUnknownFields msg = msg.workerConfigSimplePollerBehaviorUnknownFields
  setMessageUnknownFields !ufs msg = msg { workerConfigSimplePollerBehaviorUnknownFields = ufs }

instance Semigroup WorkerConfig'SimplePollerBehavior where
  a <> b = WorkerConfig'SimplePollerBehavior
    { maxPollers = case b.maxPollers of { Nothing -> a.maxPollers; x -> x }
    , workerConfigSimplePollerBehaviorUnknownFields = a.workerConfigSimplePollerBehaviorUnknownFields <> b.workerConfigSimplePollerBehaviorUnknownFields
    }

instance Monoid WorkerConfig'SimplePollerBehavior where
  mempty = defaultWorkerConfig'SimplePollerBehavior

data WorkerConfig'AutoscalingPollerBehavior = WorkerConfig'AutoscalingPollerBehavior
  { minPollers :: !(Maybe Int32)
  , maxPollers :: !(Maybe Int32)
  , initialPollers :: !(Maybe Int32)
  , workerConfigAutoscalingPollerBehaviorUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData

defaultWorkerConfig'AutoscalingPollerBehavior :: WorkerConfig'AutoscalingPollerBehavior
defaultWorkerConfig'AutoscalingPollerBehavior = WorkerConfig'AutoscalingPollerBehavior
  { minPollers = Nothing
  , maxPollers = Nothing
  , initialPollers = Nothing
  , workerConfigAutoscalingPollerBehaviorUnknownFields = []
  }

instance MessageEncode WorkerConfig'AutoscalingPollerBehavior where
  buildMessage msg =
    (maybe mempty (\v -> archVarint 8 (fromIntegral v)) msg.minPollers)
    <> (maybe mempty (\v -> archVarint 16 (fromIntegral v)) msg.maxPollers)
    <> (maybe mempty (\v -> archVarint 24 (fromIntegral v)) msg.initialPollers)
    <> encodeUnknownFields msg.workerConfigAutoscalingPollerBehaviorUnknownFields

instance MessageSize WorkerConfig'AutoscalingPollerBehavior where
  messageSize msg =
    (maybe 0 (\v -> archVarintSize (fromIntegral v)) msg.minPollers)
    + (maybe 0 (\v -> archVarintSize (fromIntegral v)) msg.maxPollers)
    + (maybe 0 (\v -> archVarintSize (fromIntegral v)) msg.initialPollers)
    + unknownFieldsSize msg.workerConfigAutoscalingPollerBehaviorUnknownFields

instance MessageDecode WorkerConfig'AutoscalingPollerBehavior where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop Nothing Nothing Nothing []
    where
      loop acc_0 acc_1 acc_2 acc_unknown_ = withTagM
        (pure (WorkerConfig'AutoscalingPollerBehavior {minPollers = acc_0, maxPollers = acc_1, initialPollers = acc_2, workerConfigAutoscalingPollerBehaviorUnknownFields = reverse acc_unknown_}))
        (\fn wt -> case fn of
          1 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop (Just v) acc_1 acc_2 acc_unknown_
          2 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop acc_0 (Just v) acc_2 acc_unknown_
          3 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop acc_0 acc_1 (Just v) acc_unknown_
          _ -> do
            uf <- captureUnknownField fn (toEnum wt)
            loop acc_0 acc_1 acc_2 (uf : acc_unknown_))

instance ProtoMessage WorkerConfig'AutoscalingPollerBehavior where
  protoMessageName _ = "temporal.api.sdk.v1.WorkerConfig.AutoscalingPollerBehavior"
  protoPackageName _ = "temporal.api.sdk.v1"
  protoDefaultValue = defaultWorkerConfig'AutoscalingPollerBehavior
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "min_pollers"
        , fdNumber = 1
        , fdTypeDesc = ScalarType Int32Field
        , fdLabel = LabelOptional
        , fdGet = \(m :: WorkerConfig'AutoscalingPollerBehavior) -> m.minPollers
        , fdSet = \v (m :: WorkerConfig'AutoscalingPollerBehavior) -> (m { minPollers = v } :: WorkerConfig'AutoscalingPollerBehavior)
        }), (2, SomeField FieldDescriptor
        { fdName = "max_pollers"
        , fdNumber = 2
        , fdTypeDesc = ScalarType Int32Field
        , fdLabel = LabelOptional
        , fdGet = \(m :: WorkerConfig'AutoscalingPollerBehavior) -> m.maxPollers
        , fdSet = \v (m :: WorkerConfig'AutoscalingPollerBehavior) -> (m { maxPollers = v } :: WorkerConfig'AutoscalingPollerBehavior)
        })
    , (3, SomeField FieldDescriptor
        { fdName = "initial_pollers"
        , fdNumber = 3
        , fdTypeDesc = ScalarType Int32Field
        , fdLabel = LabelOptional
        , fdGet = \(m :: WorkerConfig'AutoscalingPollerBehavior) -> m.initialPollers
        , fdSet = \v (m :: WorkerConfig'AutoscalingPollerBehavior) -> (m { initialPollers = v } :: WorkerConfig'AutoscalingPollerBehavior)
        })
    ]

instance IsMessage WorkerConfig'AutoscalingPollerBehavior

instance Aeson.ToJSON WorkerConfig'AutoscalingPollerBehavior where
  toJSON msg = jsonObject
      [ "minPollers" .=: msg.minPollers
      , "maxPollers" .=: msg.maxPollers
      , "initialPollers" .=: msg.initialPollers
      ]

instance Aeson.FromJSON WorkerConfig'AutoscalingPollerBehavior where
  parseJSON = Aeson.withObject "WorkerConfig'AutoscalingPollerBehavior" $ \obj -> do
    fld_minPollers <- parseFieldMaybe obj "minPollers"
    fld_maxPollers <- parseFieldMaybe obj "maxPollers"
    fld_initialPollers <- parseFieldMaybe obj "initialPollers"
    pure (defaultWorkerConfig'AutoscalingPollerBehavior
      { minPollers = maybe (defaultWorkerConfig'AutoscalingPollerBehavior.minPollers) Prelude.id fld_minPollers
      , maxPollers = maybe (defaultWorkerConfig'AutoscalingPollerBehavior.maxPollers) Prelude.id fld_maxPollers
      , initialPollers = maybe (defaultWorkerConfig'AutoscalingPollerBehavior.initialPollers) Prelude.id fld_initialPollers
      , workerConfigAutoscalingPollerBehaviorUnknownFields = []
      } :: WorkerConfig'AutoscalingPollerBehavior)

instance Hashable WorkerConfig'AutoscalingPollerBehavior where
  hashWithSalt salt msg = hashWithSalt (hashWithSalt (hashWithSalt (salt) msg.minPollers) msg.maxPollers) msg.initialPollers

instance Proto.Extension.HasExtensions WorkerConfig'AutoscalingPollerBehavior where
  messageUnknownFields msg = msg.workerConfigAutoscalingPollerBehaviorUnknownFields
  setMessageUnknownFields !ufs msg = msg { workerConfigAutoscalingPollerBehaviorUnknownFields = ufs }

instance Semigroup WorkerConfig'AutoscalingPollerBehavior where
  a <> b = WorkerConfig'AutoscalingPollerBehavior
    { minPollers = case b.minPollers of { Nothing -> a.minPollers; x -> x }
    , maxPollers = case b.maxPollers of { Nothing -> a.maxPollers; x -> x }
    , initialPollers = case b.initialPollers of { Nothing -> a.initialPollers; x -> x }
    , workerConfigAutoscalingPollerBehaviorUnknownFields = a.workerConfigAutoscalingPollerBehaviorUnknownFields <> b.workerConfigAutoscalingPollerBehaviorUnknownFields
    }

instance Monoid WorkerConfig'AutoscalingPollerBehavior where
  mempty = defaultWorkerConfig'AutoscalingPollerBehavior
data WorkerConfig'PollerBehavior
  = WorkerConfig'PollerBehavior'SimplePollerBehavior !WorkerConfig'SimplePollerBehavior
  | WorkerConfig'PollerBehavior'AutoscalingPollerBehavior !WorkerConfig'AutoscalingPollerBehavior
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
instance Aeson.ToJSON WorkerConfig'PollerBehavior where
  toJSON _ = Aeson.Null
instance Aeson.FromJSON WorkerConfig'PollerBehavior where
  parseJSON _ = fail "Cannot parse oneof from JSON"
instance Hashable WorkerConfig'PollerBehavior where
  hashWithSalt salt (WorkerConfig'PollerBehavior'SimplePollerBehavior v) = salt `hashWithSalt` (0 :: Int) `hashWithSalt` v
  hashWithSalt salt (WorkerConfig'PollerBehavior'AutoscalingPollerBehavior v) = salt `hashWithSalt` (1 :: Int) `hashWithSalt` v

defaultWorkerConfig :: WorkerConfig
defaultWorkerConfig = WorkerConfig
  { workflowCacheSize = Nothing
  , pollerBehavior = Nothing
  , workerConfigUnknownFields = []
  }

instance MessageEncode WorkerConfig where
  buildMessage msg =
    (maybe mempty (\v -> archVarint 8 (fromIntegral v)) msg.workflowCacheSize)
    <> (case msg.pollerBehavior of
      Nothing -> mempty
      Just (WorkerConfig'PollerBehavior'SimplePollerBehavior v) -> (let sz = messageSize v in archSubmessage 18 sz (buildMessage v))
      Just (WorkerConfig'PollerBehavior'AutoscalingPollerBehavior v) -> (let sz = messageSize v in archSubmessage 26 sz (buildMessage v)))
    <> encodeUnknownFields msg.workerConfigUnknownFields

instance MessageSize WorkerConfig where
  messageSize msg =
    (maybe 0 (\v -> archVarintSize (fromIntegral v)) msg.workflowCacheSize)
    + (case msg.pollerBehavior of { Nothing -> 0; Just (WorkerConfig'PollerBehavior'SimplePollerBehavior v) -> archSubmessageSize (messageSize v)
    ; Just (WorkerConfig'PollerBehavior'AutoscalingPollerBehavior v) -> archSubmessageSize (messageSize v) })
    + unknownFieldsSize msg.workerConfigUnknownFields

instance MessageDecode WorkerConfig where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop Nothing Nothing []
    where
      loop acc_0 acc_1 acc_unknown_ = withTagM
        (pure (WorkerConfig {workflowCacheSize = acc_0, pollerBehavior = acc_1, workerConfigUnknownFields = reverse acc_unknown_}))
        (\fn wt -> case fn of
          1 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop (Just v) acc_1 acc_unknown_
          2 -> do
            v <- decodeFieldMessage
            loop acc_0 (Just (WorkerConfig'PollerBehavior'SimplePollerBehavior v)) acc_unknown_
          3 -> do
            v <- decodeFieldMessage
            loop acc_0 (Just (WorkerConfig'PollerBehavior'AutoscalingPollerBehavior v)) acc_unknown_
          _ -> do
            uf <- captureUnknownField fn (toEnum wt)
            loop acc_0 acc_1 (uf : acc_unknown_))

instance ProtoMessage WorkerConfig where
  protoMessageName _ = "temporal.api.sdk.v1.WorkerConfig"
  protoPackageName _ = "temporal.api.sdk.v1"
  protoDefaultValue = defaultWorkerConfig
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "workflow_cache_size"
        , fdNumber = 1
        , fdTypeDesc = ScalarType Int32Field
        , fdLabel = LabelOptional
        , fdGet = \(m :: WorkerConfig) -> m.workflowCacheSize
        , fdSet = \v (m :: WorkerConfig) -> (m { workflowCacheSize = v } :: WorkerConfig)
        }), (2, SomeField FieldDescriptor
        { fdName = "poller_behavior"
        , fdNumber = 2
        , fdTypeDesc = MessageType "poller_behavior"
        , fdLabel = LabelOptional
        , fdGet = \(m :: WorkerConfig) -> m.pollerBehavior
        , fdSet = \v (m :: WorkerConfig) -> (m { pollerBehavior = v } :: WorkerConfig)
        })
    ]

instance IsMessage WorkerConfig

instance Aeson.ToJSON WorkerConfig where
  toJSON msg = jsonObject
      [ "workflowCacheSize" .=: msg.workflowCacheSize
      , "pollerBehavior" .=: msg.pollerBehavior
      ]

instance Aeson.FromJSON WorkerConfig where
  parseJSON = Aeson.withObject "WorkerConfig" $ \obj -> do
    fld_workflowCacheSize <- parseFieldMaybe obj "workflowCacheSize"
    fld_pollerBehavior <- parseFieldMaybe obj "pollerBehavior"
    pure (defaultWorkerConfig
      { workflowCacheSize = maybe (defaultWorkerConfig.workflowCacheSize) Prelude.id fld_workflowCacheSize
      , pollerBehavior = maybe (defaultWorkerConfig.pollerBehavior) Prelude.id fld_pollerBehavior
      , workerConfigUnknownFields = []
      } :: WorkerConfig)

instance Hashable WorkerConfig where
  hashWithSalt salt msg = hashWithSalt (hashWithSalt (salt) msg.workflowCacheSize) msg.pollerBehavior

instance Proto.Extension.HasExtensions WorkerConfig where
  messageUnknownFields msg = msg.workerConfigUnknownFields
  setMessageUnknownFields !ufs msg = msg { workerConfigUnknownFields = ufs }

instance Semigroup WorkerConfig where
  a <> b = WorkerConfig
    { workflowCacheSize = case b.workflowCacheSize of { Nothing -> a.workflowCacheSize; x -> x }
    , pollerBehavior = case b.pollerBehavior of { Nothing -> a.pollerBehavior; x -> x }
    , workerConfigUnknownFields = a.workerConfigUnknownFields <> b.workerConfigUnknownFields
    }

instance Monoid WorkerConfig where
  mempty = defaultWorkerConfig
