verbatim: { cabal-version: 3.0 }

name:         temporal-api-protos
version:      2025.10.2.0
author:       Ian Duncan
maintainer:   temporal@mercury.com
license-file: LICENSE
license:      BSD-3-Clause
build-type:   Simple
language:     Haskell2010
description:  Temporal is a durable execution system that transparently makes your code durable, fault-tolerant, and simple. These are low-level protocol buffer definitions for the Temporal API.

library:
  source-dirs: src
  dependencies:
    - base >= 4.14 && < 5
    - proto-lens-runtime
    - proto-lens-protobuf-types
  other-modules:
    - Proto.Google.Api.Annotations
    - Proto.Google.Api.Annotations_Fields
    - Proto.Google.Api.Http
    - Proto.Google.Api.Http_Fields
