verbatim: { cabal-version: 3.0 }

name:         temporal-api-protos
version:      2025.10.1.0
author:       Ian Duncan
maintainer:   temporal@mercury.com
license-file: LICENSE
license:      BSD-3-Clause
build-type:   Simple
language:     Haskell2010
description:  Temporal is a durable execution system that transparently makes your code durable, fault-tolerant, and simple. These are low-level protocol buffer definitions for the Temporal API.

library:
  source-dirs: src
  default-extensions:
    - ImportQualifiedPost
    - BangPatterns
    - LambdaCase
    - ScopedTypeVariables
  dependencies:
    - base >= 4.14 && < 5
    - wireform-proto
    - lens-family
    - aeson
    - bytestring
    - containers
    - deepseq
    - hashable
    - reflection
    - text
    - vector
    - wireform-core
  other-modules:
    - Proto.Google.Api.Annotations
    - Proto.Google.Api.Http
