<<: !include ../hpack-defaults.yaml

name:         temporal-sdk-core
build-type:   Custom

extra-source-files:
  - rust/Cargo.toml
  - rust/Cargo.lock
  - rust/src/*.rs
  - rust/temporal_bridge.h

description:  Temporal is a durable execution system that transparently makes your code durable, fault-tolerant, and simple. This is the core FFI bindings for the high-level Temporal SDK. Note that it requires Rust/Cargo to build.

ghc-options: -g -Wall

flags:
  external_lib:
    description: "Use external library (don't compile automatically)"
    default: false
    manual: true

custom-setup:
  dependencies:
    - base >= 4.7 && < 5
    - Cabal >= 3.0.0.0 && < 3.15.0.0
    - directory >= 1.3.6.0
    - filepath >= 1.3.0.2
    - unix

library:
  extra-libraries: temporal_bridge
  include-dirs:    rust
  source-dirs:     src
  other-modules:
    - Temporal.Core.CTypes
    - Temporal.Core.Client.HealthService # NOTE: WIP stub, don't expose it
    - Temporal.Internal.FFI
    - Paths_temporal_sdk_core
  dependencies:
    # core libraries
    - base >= 4.14 && < 5
    - bytestring
    - containers
    - mtl
    - stm
    - text
    - unix
    - unordered-containers
    - vector
    # hackage dependencies
    - aeson
    - async
    - atomic-primops
    - lens-family
    - monad-logger
    - network-bsd
    - proto-lens
    - unliftio
    - uuid
    # local dependencies
    - temporal-api-protos
  when:
    - condition: os(darwin)
      frameworks: [Security, CoreFoundation, SystemConfiguration]
