defaults: { local: ../hpack-defaults.yaml }

name:         temporal-sdk-core
version:      0.1.0.0
author:       Ian Duncan
maintainer:   temporal@mercury.com
license-file: LICENSE
license:      BSD-3-Clause
build-type:   Custom
language:     Haskell2010
category:     Concurrency
extra-source-files:
  - rust/Cargo.toml
  - rust/Cargo.lock
  - rust/src/*.rs
  - rust/temporal_bridge.h

ghc-options: -g -Wall

flags:
  external_lib:
    description: "Use external library (don't compile automatically)"
    default: false
    manual: true

custom-setup:
  dependencies:
    - base >= 4.7 && < 5
    - Cabal >= 3.0.0.0
    - directory >= 1.3.6.0
    - filepath >= 1.3.0.2
    - unix

library:
  extra-libraries: temporal_bridge
  include-dirs:    rust
  source-dirs:     src
  other-modules:
    - Temporal.Core.CTypes
    - Temporal.Core.Client.HealthService # NOTE: WIP stub, don't expose it
    - Temporal.Internal.FFI
  dependencies:
    # core libraries
    - base >= 4.14 && < 5
    - bytestring
    - containers
    - mtl
    - stm
    - text
    - unix
    - unordered-containers
    - vector
    # hackage dependencies
    - aeson
    - async
    - lens-family
    - network-bsd
    - proto-lens
    - unliftio
    - uuid
    # local dependencies
    - temporal-api-protos
  when:
    - condition: os(darwin)
      frameworks: [Security, CoreFoundation, SystemConfiguration]

