{-# LANGUAGE StrictData #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE DeriveAnyClass #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# OPTIONS_GHC -Wno-unused-imports -Wno-unused-matches -Wno-unused-top-binds #-}
{-# LANGUAGE DuplicateRecordFields #-}
{-# OPTIONS_GHC -Wno-ambiguous-fields #-}
-- | Auto-generated protobuf types from package @temporal.api.protocol.v1@.
--
-- __THIS FILE IS AUTO-GENERATED BY wireform. DO NOT EDIT.__
--
-- Any manual changes will be overwritten the next time code
-- generation is run.  To modify the types or instances, edit the
-- @.proto@ source file and re-run the code generator.
module Proto.Temporal.Api.Protocol.V1.Message where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Wireform.Builder as B
import Data.Int (Int32, Int64)
import Data.Text (Text)
import qualified Data.Text as T
import Data.Word (Word32, Word64)
import qualified Data.Map.Strict as Map
import qualified Data.Vector as V
import qualified Data.Vector.Unboxed as VU
import GHC.Generics (Generic)
import Control.DeepSeq (NFData(..))
import Data.Hashable (Hashable(..))
import Proto.Encode
import Proto.Decode
import qualified Data.Aeson as Aeson
import qualified Data.Aeson.Types as Aeson
import qualified Data.Aeson.Key as AesonKey
import qualified Data.Aeson.KeyMap as AesonKM
import Proto.Internal.JSON (jsonObject, (.=:), parseFieldMaybe, bytesFieldToJSON, parseBytesFieldMaybe, bytesMapFieldToJSON, parseBytesMapFieldMaybe, protoBytesToJSON)
import Data.Proxy (Proxy(..))
import Data.Reflection (Given(..), given)
import Proto.Internal.JSON.Extension qualified as PJExt
import Proto.Schema (ProtoMessage(..), SomeFieldDescriptor(..), FieldDescriptor(..), FieldTypeDescriptor(..), ScalarFieldType(..), FieldLabel'(..))
import Proto.Registry (IsMessage)
import Proto.Registry qualified
import qualified Proto.Extension
import Proto.Internal.Wire (Tag(..), WireType(..))
import Proto.Internal.Wire.Encode (putTag, putVarint, putFixed32, putFixed64,
  putFloat, putDouble, putText, putByteString, putLengthDelimited,
  putSVarint32, putSVarint64, putVarintSigned,
  varintSize, tagSize, fieldMessageSize,
  fieldVarintSize, fieldFixed32Size, fieldFixed64Size,
  fieldBoolSize, fieldFloatSize, fieldDoubleSize,
  fieldTextSize, fieldBytesSize,
  fieldSVarint32Size, fieldSVarint64Size,
  varintSize32, zigZag32, zigZag64)
import Proto.Internal.Encode.Archetype (archVarint, archSVarint32, archSVarint64,
  archFixed32, archFixed64, archFloat, archDouble, archBool,
  archString, archBytes, archSubmessage,
  archVarintSize, archStringSize, archBytesSize, archBoolSize,
  archFixed32Size, archFixed64Size, archSubmessageSize)
import qualified Proto.Google.Protobuf.Any as PB_Any

-- | Serialized FileDescriptorProto for this .proto file.
-- Decode with @Proto.Google.Protobuf.Descriptor.decodeMessage@.
fileDescriptorProtoBytes :: ByteString
fileDescriptorProtoBytes = "\x0a\x26\x74\x65\x6d\x70\x6f\x72\x61\x6c\x2f\x61\x70\x69\x2f\x70\x72\x6f\x74\x6f\x63\x6f\x6c\x2f\x76\x31\x2f\x6d\x65\x73\x73\x61\x67\x65\x2e\x70\x72\x6f\x74\x6f\x12\x18\x74\x65\x6d\x70\x6f\x72\x61\x6c\x2e\x61\x70\x69\x2e\x70\x72\x6f\x74\x6f\x63\x6f\x6c\x2e\x76\x31\x1a\x19\x67\x6f\x6f\x67\x6c\x65\x2f\x70\x72\x6f\x74\x6f\x62\x75\x66\x2f\x61\x6e\x79\x2e\x70\x72\x6f\x74\x6f\x22\x90\x01\x0a\x07\x4d\x65\x73\x73\x61\x67\x65\x12\x0a\x0a\x02\x69\x64\x18\x01\x20\x01\x28\x09\x12\x1c\x0a\x14\x70\x72\x6f\x74\x6f\x63\x6f\x6c\x5f\x69\x6e\x73\x74\x61\x6e\x63\x65\x5f\x69\x64\x18\x02\x20\x01\x28\x09\x12\x21\x0a\x04\x62\x6f\x64\x79\x18\x05\x20\x01\x28\x0b\x32\x13\x67\x6f\x6f\x67\x6c\x65\x2e\x70\x72\x6f\x74\x6f\x62\x75\x66\x2e\x41\x6e\x79\x12\x10\x0a\x08\x65\x76\x65\x6e\x74\x5f\x69\x64\x18\x03\x20\x01\x28\x03\x12\x15\x0a\x0d\x63\x6f\x6d\x6d\x61\x6e\x64\x5f\x69\x6e\x64\x65\x78\x18\x04\x20\x01\x28\x03\x42\x0f\x0a\x0d\x73\x65\x71\x75\x65\x6e\x63\x69\x6e\x67\x5f\x69\x64\x62\x06\x70\x72\x6f\x74\x6f\x33"


data Message = Message
  { id :: !(Maybe Text)
  , protocolInstanceId :: !(Maybe Text)
  , body :: !(Maybe PB_Any.Any)
  , sequencingId :: !(Maybe Message'SequencingId)
  , messageUnknownFields :: ![UnknownField]
  }
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
data Message'SequencingId
  = Message'SequencingId'EventId {-# UNPACK #-} !Int64
  | Message'SequencingId'CommandIndex {-# UNPACK #-} !Int64
  deriving stock (Show, Eq, Generic)
  deriving anyclass NFData
instance Aeson.ToJSON Message'SequencingId where
  toJSON _ = Aeson.Null
instance Aeson.FromJSON Message'SequencingId where
  parseJSON _ = fail "Cannot parse oneof from JSON"
instance Hashable Message'SequencingId where
  hashWithSalt salt (Message'SequencingId'EventId v) = salt `hashWithSalt` (0 :: Int) `hashWithSalt` v
  hashWithSalt salt (Message'SequencingId'CommandIndex v) = salt `hashWithSalt` (1 :: Int) `hashWithSalt` v

defaultMessage :: Message
defaultMessage = Message
  { id = Nothing
  , protocolInstanceId = Nothing
  , body = Nothing
  , sequencingId = Nothing
  , messageUnknownFields = []
  }

instance MessageEncode Message where
  buildMessage msg =
    (maybe mempty (\v -> archString 10 v) msg.id)
    <> (maybe mempty (\v -> archString 18 v) msg.protocolInstanceId)
    <> (maybe mempty (\v -> let sz = messageSize v in archSubmessage 42 sz (buildMessage v)) msg.body)
    <> (case msg.sequencingId of
      Nothing -> mempty
      Just (Message'SequencingId'EventId v) -> archVarint 24 (fromIntegral v)
      Just (Message'SequencingId'CommandIndex v) -> archVarint 32 (fromIntegral v))
    <> encodeUnknownFields msg.messageUnknownFields

instance MessageSize Message where
  messageSize msg =
    (maybe 0 (\v -> archStringSize v) msg.id)
    + (maybe 0 (\v -> archStringSize v) msg.protocolInstanceId)
    + (maybe 0 (\v -> archSubmessageSize (messageSize v)) msg.body)
    + (case msg.sequencingId of { Nothing -> 0; Just (Message'SequencingId'EventId v) -> archVarintSize (fromIntegral v)
    ; Just (Message'SequencingId'CommandIndex v) -> archVarintSize (fromIntegral v) })
    + unknownFieldsSize msg.messageUnknownFields

instance MessageDecode Message where
  {-# INLINE messageDecoder #-}
  messageDecoder = loop Nothing Nothing Nothing Nothing []
    where
      loop acc_0 acc_1 acc_2 acc_3 acc_unknown_ = withTagM
        (pure (Message {id = acc_0, protocolInstanceId = acc_1, body = acc_2, sequencingId = acc_3, messageUnknownFields = reverse acc_unknown_}))
        (\fn wt -> case fn of
          1 -> do
            v <- decodeFieldString
            loop (Just v) acc_1 acc_2 acc_3 acc_unknown_
          2 -> do
            v <- decodeFieldString
            loop acc_0 (Just v) acc_2 acc_3 acc_unknown_
          5 -> do
            v <- decodeFieldMessage
            loop acc_0 acc_1 (Just v) acc_3 acc_unknown_
          3 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop acc_0 acc_1 acc_2 (Just (Message'SequencingId'EventId v)) acc_unknown_
          4 -> do
            v <- (fromIntegral <$> decodeFieldVarint)
            loop acc_0 acc_1 acc_2 (Just (Message'SequencingId'CommandIndex v)) acc_unknown_
          _ -> do
            uf <- captureUnknownField fn (toEnum wt)
            loop acc_0 acc_1 acc_2 acc_3 (uf : acc_unknown_))

instance ProtoMessage Message where
  protoMessageName _ = "temporal.api.protocol.v1.Message"
  protoPackageName _ = "temporal.api.protocol.v1"
  protoDefaultValue = defaultMessage
  protoFileDescriptorBytes _ = fileDescriptorProtoBytes
  protoFieldDescriptors _ = Map.fromList
    [ (1, SomeField FieldDescriptor
        { fdName = "id"
        , fdNumber = 1
        , fdTypeDesc = ScalarType StringField
        , fdLabel = LabelOptional
        , fdGet = \(m :: Message) -> m.id
        , fdSet = \v (m :: Message) -> (m { id = v } :: Message)
        }), (2, SomeField FieldDescriptor
        { fdName = "protocol_instance_id"
        , fdNumber = 2
        , fdTypeDesc = ScalarType StringField
        , fdLabel = LabelOptional
        , fdGet = \(m :: Message) -> m.protocolInstanceId
        , fdSet = \v (m :: Message) -> (m { protocolInstanceId = v } :: Message)
        })
    , (5, SomeField FieldDescriptor
        { fdName = "body"
        , fdNumber = 5
        , fdTypeDesc = MessageType "google.protobuf.Any"
        , fdLabel = LabelOptional
        , fdGet = \(m :: Message) -> m.body
        , fdSet = \v (m :: Message) -> (m { body = v } :: Message)
        })
    , (3, SomeField FieldDescriptor
        { fdName = "sequencing_id"
        , fdNumber = 3
        , fdTypeDesc = MessageType "sequencing_id"
        , fdLabel = LabelOptional
        , fdGet = \(m :: Message) -> m.sequencingId
        , fdSet = \v (m :: Message) -> (m { sequencingId = v } :: Message)
        })
    ]

instance IsMessage Message

instance Aeson.ToJSON Message where
  toJSON msg = jsonObject
      [ "id" .=: msg.id
      , "protocolInstanceId" .=: msg.protocolInstanceId
      , "body" .=: msg.body
      , "sequencingId" .=: msg.sequencingId
      ]

instance Aeson.FromJSON Message where
  parseJSON = Aeson.withObject "Message" $ \obj -> do
    fld_id <- parseFieldMaybe obj "id"
    fld_protocolInstanceId <- parseFieldMaybe obj "protocolInstanceId"
    fld_body <- parseFieldMaybe obj "body"
    fld_sequencingId <- parseFieldMaybe obj "sequencingId"
    pure (defaultMessage
      { id = maybe (defaultMessage.id) Prelude.id fld_id
      , protocolInstanceId = maybe (defaultMessage.protocolInstanceId) Prelude.id fld_protocolInstanceId
      , body = maybe (defaultMessage.body) Prelude.id fld_body
      , sequencingId = maybe (defaultMessage.sequencingId) Prelude.id fld_sequencingId
      , messageUnknownFields = []
      } :: Message)

instance Hashable Message where
  hashWithSalt salt msg = hashWithSalt (hashWithSalt (hashWithSalt (hashWithSalt (salt) msg.id) msg.protocolInstanceId) msg.body) msg.sequencingId

instance Proto.Extension.HasExtensions Message where
  messageUnknownFields msg = msg.messageUnknownFields
  setMessageUnknownFields !ufs msg = msg { messageUnknownFields = ufs }

instance Semigroup Message where
  a <> b = Message
    { id = case b.id of { Nothing -> a.id; x -> x }
    , protocolInstanceId = case b.protocolInstanceId of { Nothing -> a.protocolInstanceId; x -> x }
    , body = case b.body of { Nothing -> a.body; x -> x }
    , sequencingId = case b.sequencingId of { Nothing -> a.sequencingId; x -> x }
    , messageUnknownFields = a.messageUnknownFields <> b.messageUnknownFields
    }

instance Monoid Message where
  mempty = defaultMessage
