defaults:
  local: ../hpack-common/defaults.yaml

verbatim: { cabal-version: 3.0 }

name:         temporal-sdk-optimal-codec
version:      "0.0.1.0"
author:       Ian Duncan
maintainer:   temporal@mercury.com
license-file: LICENSE
license:      BSD-3-Clause
build-type:   Simple
language:     Haskell2010

dependencies:
- base
- temporal-sdk
- if-instance >= 0.5
- containers

library:
  source-dirs: src
  other-modules: []
