defaults:
  local: ../hpack-common/defaults.yaml

verbatim: { cabal-version: 3.0 }

name:         temporal-sdk
version:      "0.0.1.0"
author:       Ian Duncan
maintainer:   temporal@mercury.com
license-file: LICENSE
license:      BSD-3-Clause
build-type:   Simple
language:     Haskell2010

dependencies:
- base
- proto-lens
- proto-lens-protobuf-types
- temporal-api-protos
- temporal-sdk-core
- bytestring
- discover-instances
- mtl
- transformers
- text
- th-lift-instances
- aeson
- unordered-containers
- vector
- async
- unliftio
- lens-family
- scientific
- uuid
- uuid-types
- stm
- time
- containers
- hashable
- monad-logger
- random
- exceptions
- ghc
- template-haskell
- conduit
- annotated-exception
- require-callstack
- hs-opentelemetry-api
- hs-opentelemetry-propagator-w3c
- base64
- zlib
- network
- split
- these
- first-class-families
- validation-selective
- vault

library:
  source-dirs: src
  other-modules:
  - Temporal.Activity.Definition
  - Temporal.Activity.Worker
  - Temporal.Client.Types
  - Temporal.Client.AsyncActivity
  - Temporal.Client.Workflow
  - Temporal.Common
  - Temporal.Common.Async
  - Temporal.Common.TimeoutType
  - Temporal.Coroutine
  - Temporal.Workflow.Definition
  - Temporal.WorkflowInstance
  - Temporal.Workflow.Worker
  - Temporal.Workflow.Eval
  - Temporal.Workflow.WorkflowInstance
  - Temporal.Worker.Types
  - Temporal.Activity.Types
  - Temporal.Workflow.Unsafe.Handle
  - Temporal.Workflow.Internal.Instance
  - Temporal.Workflow.Internal.Monad
  - Temporal.Workflow.Signal
  - Temporal.Workflow.Query
  - Temporal.Workflow.Types
  - Temporal.Logging
  - Temporal.SearchAttributes.Internal
  - Temporal.TH.Classes
  - Temporal.TH.Internal
  when:
  - condition: false
    other-modules: Paths_temporal_sdk
  - condition: true
    exposed-modules: Paths_temporal_sdk

tests:
  temporal-sdk-tests:
    ghc-options: -g -threaded -rtsopts -with-rtsopts=-N
    build-tools:
      "hspec-discover:hspec-discover"
    dependencies:
      - base
      - temporal-sdk
      - temporal-sdk-core
      - bytestring
      - directory
      - hedgehog
      - hspec
      - hspec-api
      - hspec-hedgehog
      - text
      - uuid
      - monad-logger
      - exceptions
      - mtl
      - transformers
      - time
      - unliftio
      - proto-lens
      - containers
      - require-callstack
      - hs-opentelemetry-sdk
      - resourcet
    main: Main.hs
    source-dirs: test
    other-modules:
      Spec,
      ConcurrentAccessSpec,
      AsyncCompletionSpec,
      DurationSpec,
      IntegrationSpec,
      IntegrationSpec.HangingWorkflow,
      IntegrationSpec.TimeoutsInWorkflows,
      Common,
      THCompiles
